### ISSUE TITLE
get current time in city

### ISSUE THREAD

**Issue by dkravcovs** [darkalor/junkbot#4]
E.g. 
- get current time in Riga
- what is the time in London when it is 10:00 in Riga
- etc?

Could check:
- https://developers.google.com/maps/documentation/timezone/intro
- https://timezonedb.com/api

**Comment by apabinc** [comment]
> get current time in Riga

/time Riga

> what is the time in London when it is 10:00 in Riga

/time London Riga 10:00
/time London Riga(10:00)
/time London -w Riga 10:00 // -h stands for 'when'
